#!/bin/bash

# Cd to deploy directory
cd "$(dirname "$0")"

# Remove old package
rm r.spl

# Increase build number
BUILD=`cat .build`
BUILD=$(($BUILD+1))
echo $BUILD > .build

# Ask for new version number
VERSION=`cat .version`
read -p "Version ($VERSION): " NEW_VERSION
if [ ! -z "$NEW_VERSION" ]; then
	VERSION="$NEW_VERSION"
fi
echo $VERSION > .version

# Update app config
perl -i -pe "s/^build\s*=.*/build = $BUILD/g" ../default/app.conf
perl -i -pe "s/^version\s*=.*/version = $VERSION/g" ../default/app.conf

cd ../..
tar -zcf r/deploy/r.spl --exclude='r/private' --exclude='r/deploy' --exclude='r/.git' --exclude='r/.git' --exclude='r/.gitignore' --exclude='README.md' --exclude='r/bin/*_test.py' --exclude='r/bin/test' --exclude='r/bin/test_*.py' -X r/.gitignore r

